


export const hrefs = {
    default: "/",
    headless: {
        default: "/headless",
        quickStart: {
            default: "/headless/quick-start",
            installation: "/headless/quick-start/installation",
            gettingStarted: "/headless/quick-start/getting-started",
        },
        featureApis: {
            default: "/headless/feature-apis",
            columnFilters: "/headless/feature-apis/column-filters",
            columnFaceting: "/headless/feature-apis/column-faceting",
            columnOrdering: "/headless/feature-apis/column-ordering",
            columnPinning: "/headless/feature-apis/column-pinning",
            columnSizing: "/headless/feature-apis/column-sizing",
            columnVisibility: "/headless/feature-apis/column-visibility",
            globalSearch: "/headless/feature-apis/global-search",
            sorting: "/headless/feature-apis/sorting",
            grouping: "/headless/feature-apis/grouping",
            expanding: "/headless/feature-apis/expanding",
            pagination: "/headless/feature-apis/pagination",
            rowPinning: "/headless/feature-apis/row-pinning",
            rowSelection: "/headless/feature-apis/row-selection",
        },
        examples: {
            default: "/headless/examples",
            basic: "/headless/examples/basic",
            columnFilters: "/headless/examples/column-filters",
            columnFiltersFaceted: "/headless/examples/column-filters-faceted",
            columnOrdering: "/headless/examples/column-ordering",
            columnPinning: "/headless/examples/column-pinning",
            columnSizing: "/headless/examples/column-sizing",
            columnVisibility: "/headless/examples/column-visibility",
            editableData: "/headless/examples/editable-data",
            expanding: "/headless/examples/expanding",
            fullyControlled: "/headless/examples/fully-controlled",
            grouping: "/headless/examples/grouping",
            pagination: "/headless/examples/pagination",
            paginationControlled: "/headless/examples/pagination-controlled",
            sorting: "/headless/examples/sorting",
            subComponents: "/headless/examples/sub-components",
            virtualization: "/headless/examples/virtualization",
            rowSelection: "/headless/examples/row-selection",
        }
    },
    shadcnSvelte: {
        default: "/shadcn-svelte",
        quickStart: {
            default: "/shadcn-svelte/quick-start",
            installation: "/shadcn-svelte/quick-start/installation",
            gettingStarted: "/shadcn-svelte/quick-start/getting-started",
        },
        playground: {
            default: "/shadcn-svelte/playground",
            performance: "/shadcn-svelte/playground/performance",
        },
        examples: {
            default: "/shadcn-svelte/examples",
            basic: "/shadcn-svelte/examples/basic",
            columnAlignment: "/shadcn-svelte/examples/column-alignment",
            columnFilters: "/shadcn-svelte/examples/column-filters",
            columnFiltersFaceted: "/shadcn-svelte/examples/column-filters-faceted",
            columnOrdering: "/shadcn-svelte/examples/column-ordering",
            columnPinning: "/shadcn-svelte/examples/column-pinning",
            columnSizing: "/shadcn-svelte/examples/column-sizing",
            columnVisibility: "/shadcn-svelte/examples/column-visibility",
            contextMenu: "/shadcn-svelte/examples/context-menu",
            copyingData: "/shadcn-svelte/examples/copying-data",
            editableData: "/shadcn-svelte/examples/editable-data",
            expanding: "/shadcn-svelte/examples/expanding",
            exportingData: "/shadcn-svelte/examples/exporting-data",
            fullscreen: "/shadcn-svelte/examples/fullscreen",
            fullyControlled: "/shadcn-svelte/examples/fully-controlled",
            grouping: "/shadcn-svelte/examples/grouping",
            mobile: "/shadcn-svelte/examples/mobile",
            pagination: "/shadcn-svelte/examples/pagination",
            paginationControlled: "/shadcn-svelte/examples/pagination-controlled",
            rowSelection: "/shadcn-svelte/examples/row-selection",
            scrollToTop: "/shadcn-svelte/examples/scroll-to-top",
            sorting: "/shadcn-svelte/examples/sorting",
            spacing: "/shadcn-svelte/examples/spacing",
            statusIndicator: "/shadcn-svelte/examples/status-indicator",
            subComponents: "/shadcn-svelte/examples/sub-components",
            textSizing: "/shadcn-svelte/examples/text-sizing",
            virtualization: "/shadcn-svelte/examples/virtualization",
        }
    }
}